<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TransactionsUpdatesController;
use FortisAPILib\Exceptions;

class TransactionsUpdatesControllerTest extends BaseTestController
{
    /**
     * @var TransactionsUpdatesController TransactionsUpdatesController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTransactionsUpdatesController();
    }

    public function testTestVoid()
    {
        // Parameters for the API call
        $transactionId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->void($transactionId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Transaction","data":{"additional_amounts":[{"type":"cashback","amount' .
                '":10,"account_type":"credit","currency":840}],"billing_address":{"city":"Novi",' .
                '"state":"Michigan","postal_code":"48375","phone":"3339998822"},"checkin_date":"' .
                '2021-12-01","checkout_date":"2021-12-01","clerk_number":"AE1234","contact_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","custom_data":{},"customer_id":"customerid","descript' .
                'ion":"some description","iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5' .
                'vdEJhc2U2NEVuY29kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY2' .
                '9kZWQ=","installment":true,"installment_number":1,"installment_count":1,"locati' .
                'on_api_id":"location-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"n' .
                'o_show":false,"notification_email_address":"johnsmith@smiths.com","order_number' .
                '":"433659378839","po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","recurring":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","token_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","account_vault_api_id":"token1234abcd","token_api_' .
                'id":"token1234abcd","_joi":{"conditions":{}},"active":true,"description":"Descr' .
                'iption","end_date":"2021-12-01","installment_total_count":20,"interval":1,"inte' .
                'rval_type":"d","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"' .
                'payment_method":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recur' .
                'ring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","sta' .
                'rt_date":"2021-12-01","status":"active","transaction_amount":300,"terms_agree":' .
                'true,"terms_agree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","' .
                'recurring_c2":"recurring custom data 2","recurring_c3":"recurring custom data 3' .
                '","send_to_proc_as_recur":true,"id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":' .
                '"2021-12-01","created_ts":1422040992,"modified_ts":1422040992,"recurring_type_i' .
                'd":"i","installment_amount_total":99999999},"recurring_number":1,"room_num":"30' .
                '3","room_rate":95,"save_account":false,"save_account_title":"John Account","sub' .
                'total_amount":599,"surcharge_amount":100,"tags":[{"location_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","title":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":' .
                '1422040992,"modified_ts":1422040992}],"tax":0,"tip_amount":0,"transaction_amoun' .
                't":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-abcd123","t' .
                'ransaction_c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3' .
                '":"custom-data-3","bank_funded_only_override":false,"allow_partial_authorizatio' .
                'n_override":false,"auto_decline_cvv_override":false,"auto_decline_street_overri' .
                'de":false,"auto_decline_zip_override":false,"id":"11e95f8ec39de8fbdb0a4f1a","cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","account_holder_name":"smith","account_type":"checking","token_id":"11e' .
                '95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","auth_amount":' .
                '1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_present":true' .
                ',"card_present":true,"check_number":"8520748520963","customer_ip":"192.168.0.10' .
                '","cvv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID":"a0000000042' .
                '203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800' .
                '","TVR":"0800008000"},"first_six":"545454","last_four":"5454","payment_method":' .
                '"cc","terminal_serial_number":"1234567890","transaction_settlement_status":null' .
                ',"charge_back_date":"2021-12-01","is_recurring":true,"notification_email_sent":' .
                '"true","par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"recurring_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code":101,"tra' .
                'nsaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","void_date"' .
                ':"2021-12-01","batch":"2","terms_agree":true,"response_message":null,"return_da' .
                'te":"2021-12-01","trx_source_id":8,"routing_number":"051904524","trx_source_cod' .
                'e":8,"paylink_id":"11e95f8ec39de8fbdb0a4f1a","account_vault":{"account_holder_n' .
                'ame":"John Smith","account_number":"545454545454545","account_vault_api_id":"ac' .
                'countvaultabcd","token_api_id":"tokenabcd","accountvault_c1":"accountvault cust' .
                'om 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountvault' .
                ' custom 3","token_c1":"token custom 1","token_c2":"token custom 2","token_c3":"' .
                'token custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"' .
                'Michigan","postal_code":"48375","phone":"3339998822"},"contact_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","customer_id":"123456","identity_verification":{"dl_state":"MI",' .
                '"dl_number":"1235567","ssn4":"8527","dob_year":"1980"},"location_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","previous_account_vault_api_id":"previousaccountvault123456","' .
                'previous_token_api_id":"previousaccountvault123456","previous_account_vault_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","previous_token_id":"11e95f8ec39de8fbdb0a4f1a","pre' .
                'vious_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terms_agree":true,"terms_agre' .
                'e_ip":"192.168.0.10","title":"Test CC Account","_joi":{},"id":"11e95f8ec39de8fb' .
                'db0a4f1a","account_type":"checking","active":true,"cau_summary_status_id":1,"cr' .
                'eated_ts":1422040992,"e_serial_number":"1234567890","e_track_data":null,"e_form' .
                'at":null,"e_keyed_data":null,"expiring_in_months":null,"exp_date":"0722","first' .
                '_six":"700953","has_recurring":false,"last_four":"3657","modified_ts":142204099' .
                '2,"payment_method":"cc","ticket":null,"track_data":null},"quick_invoice":{"loca' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","title":"My terminal","cc_product_transacti' .
                'on_id":"11e95f8ec39de8fbdb0a4f1a","ach_product_transaction_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","due_date":"2021-12-01","item_list":[{"name":"Bread","amount":2015}]' .
                ',"allow_overpayment":true,"bank_funded_only_override":true,"email":"email@domai' .
                'n.com","contact_id":"11e95f8ec39de8fbdb0a4f1a","contact_api_id":"contact12345",' .
                '"quick_invoice_api_id":"quickinvoice12345","customer_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","expire_date":"2021-12-01","allow_partial_pay":true,"attach_files_to_email' .
                '":true,"send_email":true,"invoice_number":"invoice12345","item_header":"Quick i' .
                'nvoice header sample","item_footer":"Thank you","amount_due":245.36,"notificati' .
                'on_email":"email@domain.com","status_id":1,"status_code":1,"note":"some note","' .
                'notification_days_before_due_date":3,"notification_days_after_due_date":7,"noti' .
                'fication_on_due_date":true,"send_text_to_pay":true,"files":[null],"remaining_ba' .
                'lance":245.36,"single_payment_min_amount":500,"single_payment_max_amount":50000' .
                '0,"cell_phone":"3339998822","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","mod' .
                'ified_user_id":"11e95f8ec39de8fbdb0a4f1a","active":true,"payment_status_id":1,"' .
                'is_active":true},"log_emails":[{"subject":"Payment Receipt - 12skiestech","body' .
                '":"This email is being sent from a server.","source_address":"\\"12skiestech A7' .
                't3qi\\" <noreply@zeamster.email>","return_path":"\\"12skiestech A7t3qi\\" <nore' .
                'ply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4-8a39-4a5b-8d5d-68' .
                'd51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","reason_sent":"Contac' .
                't Email","reason_model":"Transaction","reason_model_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"11e95f8ec39de8fbdb0' .
                'a4f1a","created_ts":1422040992}],"is_voidable":true,"is_token":true,"is_account' .
                'vault":true,"is_reversible":true,"is_refundable":true,"is_completable":true,"is' .
                '_settled":true,"created_user":{"account_number":"5454545454545454","branding_do' .
                'main_url":"{branding_domain_url}","cell_phone":"3339998822","company_name":"For' .
                'tis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birt' .
                'h":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.co' .
                'm","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last' .
                '_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":' .
                '"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":nu' .
                'll,"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry' .
                '_page":"dashboard","page_size":2,"report_export_type":"csv","process_method":"v' .
                'irtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{us' .
                'er_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type' .
                '_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","status_id":1,"api_only":false,"is_invitation":false,"address":{"city":"Novi' .
                '","state":"MI","postal_code":"48375","country":"US"},"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":' .
                '1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a' .
                '","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_' .
                'time":"2019-03-11T10:38:26-0700"},"location":{"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'created_ts":1422040992,"modified_ts":1422040992,"account_number":"5454545454545' .
                '454","address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US"' .
                '},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_de' .
                'fault":true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5' .
                'f1e092242dda","email_reply_to":"email@domain.com","fax":"3339998822","location_' .
                'api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","locati' .
                'on_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name"' .
                ':"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone":"' .
                '1021021209","tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","sho' .
                'w_contact_notes":true,"show_contact_files":true,"ticket_hash_key":"A5F443CADF4A' .
                'E34BBCAADF4"},"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_numb' .
                'er":"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smith' .
                '","cell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state":"' .
                'Michigan","postal_code":"48375","country":"US"},"company_name":"Fortis Payment ' .
                'Systems, LLC","header_message":"This is a sample message for you","date_of_birt' .
                'h":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phon' .
                'e":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exist' .
                's":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","paren' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"c' .
                'hangelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"' .
                'CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","use' .
                'r_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb' .
                '0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_va' .
                'lue":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@d' .
                'omain.com","first_name":"Bob","last_name":"Fairview"}}],"product_transaction":{' .
                '"processor_version":"1_0_0","title":"My terminal","payment_method":"cc","proces' .
                'sor":"zgate","mcc":"1111","tax_surcharge_config":2,"partner":"standalone","loca' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},"processor_data":{},"vt_cler' .
                'k_number":true,"vt_billing_phone":true,"vt_enable_tip":true,"ach_allow_debit":t' .
                'rue,"ach_allow_credit":true,"ach_allow_refund":true,"vt_cvv":true,"vt_street":t' .
                'rue,"vt_zip":true,"vt_order_num":true,"vt_enable":true,"receipt_show_contact_na' .
                'me":true,"display_avs":true,"card_type_visa":true,"card_type_mc":true,"card_typ' .
                'e_disc":true,"card_type_amex":true,"card_type_diners":true,"card_type_jcb":true' .
                ',"invoice_location":true,"allow_partial_authorization":true,"allow_recurring_pa' .
                'rtial_authorization":true,"auto_decline_cvv":true,"auto_decline_street":true,"a' .
                'uto_decline_zip":true,"split_payments_allow":true,"vt_show_custom_fields":true,' .
                '"receipt_show_custom_fields":true,"vt_override_sales_tax_allowed":true,"vt_enab' .
                'le_sales_tax":true,"vt_require_zip":true,"vt_require_street":true,"auto_decline' .
                '_cavv":true,"current_batch":34,"dup_check_per_batch":null,"paylink_allow":false' .
                ',"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"sales_' .
                'office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"surcha' .
                'rge_id":"11e95f8ec39de8fbdb0a4f1a","level3_default":{},"cau_subscribe_type_id":' .
                '0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_billing_gro' .
                'up_id":"nofees","account_number":"12345678","run_avs_on_accountvault_create":fa' .
                'lse,"accountvault_expire_notification_email_enable":false,"debit_allow_void":fa' .
                'lse,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_currency":tru' .
                'e,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_company_nam' .
                'e":false,"receipt_show_company_name":false,"bank_funded_only":false,"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts":142204' .
                '0992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec' .
                '39de8fbdb0a4f1a"},"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title"' .
                ':"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modifie' .
                'd_ts":1422040992}],"tagTransactions":[{"id":"11e95f8ec39de8fbdb0a4f1a","tag_id"' .
                ':"Tag ID","transaction_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"' .
                'modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_' .
                'user_id":"11e95f8ec39de8fbdb0a4f1a"}],"declined_recurring_notification":{"id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","modified_ts":1422040992,"modified_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"},"payment_recurring_notification":{"id":"11e95f8ec39de8fbdb0a4f1a","cre' .
                'ated_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_ts":' .
                '1422040992,"modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"developer_company":{' .
                '"title":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts' .
                '":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"terminal":{"location_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","default_product_transaction_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","terminal_application_id":"11e95f8ec39de8fbdb0a4f1a","terminal_cvm_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","terminal_manufacturer_code":"1","title":"My terminal"' .
                ',"mac_address":"3D:F2:C9:A6:B3:4F","local_ip_address":"192.168.0.10","port":100' .
                '09,"serial_number":"1234567890","terminal_number":"973456789012367","terminal_t' .
                'imeouts":{"card_entry_timeout":47,"device_terms_prompt_timeout":30,"overall_tim' .
                'eout":125,"pin_entry_timeout":40,"signature_input_timeout":35,"signature_submit' .
                '_timeout":38,"status_display_time":12,"tip_cashback_timeout":25,"transaction_ti' .
                'meout":17},"tip_percents":{"percent_1":0,"percent_2":2,"percent_3":99},"header_' .
                'line_1":"line 1 sample","header_line_2":"line 2 sample","header_line_3":"line 3' .
                ' sample","header_line_4":"line 4 sample","header_line_5":"line 5 sample","trail' .
                'er_line_1":"trailer 1 sample","trailer_line_2":"trailer 2 sample","trailer_line' .
                '_3":"trailer 3 sample","trailer_line_4":"trailer 4 sample","trailer_line_5":"tr' .
                'ailer 5 sample","default_checkin":"2021-12-01","default_checkout":"2021-12-01",' .
                '"default_room_rate":56,"default_room_number":"303","debit":false,"emv":false,"c' .
                'ashback_enable":false,"print_enable":false,"sig_capture_enable":false,"is_provi' .
                'sioned":false,"tip_enable":false,"validated_decryption":false,"communication_ty' .
                'pe":"http","active":true,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204099' .
                '2,"modified_ts":1422040992,"last_registration_ts":1422040992,"created_user_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"host' .
                'ed_payment_page":{"user_id":"11e95f8ec39de8fbdb0a4f1a","location_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","location_api_id":null,"product_transaction_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","title":"Sample title","redirect_url_delay":15,"min_payment_amount' .
                '":0,"max_payment_amount":9999999999,"redirect_url_on_approve":null,"redirect_ur' .
                'l_on_decline":null,"field_configuration":{"css_mini":true,"stack":"vertical","h' .
                'eader":{"settings":{"enabled":true,"columns":1,"rows":1},"fields":[{"id":"trans' .
                'action_amount","label":"Header","field_type":"heading","position":["1"],"requir' .
                'ed":true,"readonly":true,"visible":true}]},"body":{"settings":{"enabled":true,"' .
                'columns":1,"rows":1},"fields":[{"id":"transaction_amount","label":"Header","fie' .
                'ld_type":"heading","position":["1"],"required":true,"readonly":true,"visible":t' .
                'rue}]},"footer":{"settings":{"enabled":true,"columns":1,"rows":1},"fields":[{"i' .
                'd":"transaction_amount","label":"Header","field_type":"heading","position":["1"' .
                '],"required":true,"readonly":true,"visible":true}]}},"encryption_key":null,"sty' .
                'lesheet_url":null,"parent_send_message":true,"hide_optional_fields":true,"id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb' .
                '0a4f1a"},"transaction_level3":{"id":"11e95f8ec39de8fbdb0a4f1a","transaction_id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","level3_data":{"destination_country_code":"840","du' .
                'ty_amount":0,"freight_amount":0,"national_tax":2,"sales_tax":200,"shipfrom_zip_' .
                'code":"AZ1234","shipto_zip_code":"FL1234","tax_amount":10,"tax_exempt":"0","cus' .
                'tomer_vat_registration":"12345678","merchant_vat_registration":"123456","order_' .
                'date":"171006","summary_commodity_code":"C1K2","tax_rate":0,"unique_vat_ref_num' .
                'ber":"vat1234","line_items":[{"description":"cool drink","commodity_code":"cc12' .
                '3456","discount_amount":0,"other_tax_amount":0,"product_code":"fanta123456","qu' .
                'antity":12,"tax_amount":4,"tax_rate":0,"unit_code":"gll","unit_cost":3,"alterna' .
                'te_tax_id":"1234","debit_credit":"C","discount_rate":11,"tax_type_applied":"22"' .
                ',"tax_type_id":"11"}]}},"developer_company_id":"Sample Developer Company ID","t' .
                'ransaction_histories":[{"transaction_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95' .
                'f8ec39de8fbdb0a4f1a","status_id":101,"event_date_ts":1422040992,"location_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992}],"s' .
                'urcharge_transaction":{"id":"11e95f8ec39de8fbdb0a4f1a","model_name":"Model Name' .
                '","transaction_id":"11e95f8ec39de8fbdb0a4f1a","surcharge_fee":0,"surcharge_rate' .
                '":0,"surcharge_amount":null,"surcharge_transaction_min":null,"surcharge_transac' .
                'tion_max":null,"created":1422040992,"modified":1422040992,"created_user_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"},"surchar' .
                'ge":{"surcharge_fee":10,"surcharge_rate":1,"product_transaction_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","apply_to_user_type_id":"11e95f8ec39de8fbdb0a4f1a","title":null' .
                ',"surcharge_label":null,"surcharge_transaction_product_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_user_id":"11e95f8ec39de8fbdb0a4' .
                'f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"mod' .
                'ified_ts":1422040992},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAA' .
                'sCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+N' .
                'xyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTg' .
                'nNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8' .
                'A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu' .
                '6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b' .
                '4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6' .
                'aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYa' .
                'x7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4p' .
                'CRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/' .
                'fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb' .
                '/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tV' .
                'cMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARY' .
                'RHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"' .
                'modified_ts":1422040992},"reason_code":{"id":50,"title":"Sample Title"},"type":' .
                '{"id":50,"title":"Sample Title"},"status":{"id":50,"title":"Sample Title"},"tra' .
                'nsaction_batch":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"produ' .
                'ct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","processing_status_id":2,"batch_n' .
                'um":4,"is_open":0,"settlement_file_name":"settement_file.txt","batch_close_ts":' .
                '1531423693,"batch_close_detail":"BATCH_MISMATCH","total_sale_amount":2342,"tota' .
                'l_sale_count":21,"total_refund_amount":2342,"total_refund_count":18,"total_void' .
                '_amount":2342,"total_void_count":17},"transaction_splits":[{"transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","contact_id":"11e95f8ec39de8fbdb0a4f1a","amount":10,"i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f' .
                '8ec39de8fbdb0a4f1a"}],"postback_logs":[{"id":"11e95f8ec39de8fbdb0a4f1a","postba' .
                'ck_config_id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","next_run_ts":1422040992,"created_ts":1422040992,"model_id":"11e95f8ec39de8' .
                'fbdb0a4f1a"}],"currency_type":{"id":50,"title":"Sample Title"},"transaction_ref' .
                'erences":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_use' .
                'r_id":"11e95f8ec39de8fbdb0a4f1a"}]}}'
            )))
            ->assert();
    }
}
