<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\EmvReceiptData;

/**
 * Builder for model EmvReceiptData
 *
 * @see EmvReceiptData
 */
class EmvReceiptDataBuilder
{
    /**
     * @var EmvReceiptData
     */
    private $instance;

    private function __construct(EmvReceiptData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new emv receipt data Builder object.
     */
    public static function init(): self
    {
        return new self(new EmvReceiptData());
    }

    /**
     * Sets aid field.
     */
    public function aID(?string $value): self
    {
        $this->instance->setAID($value);
        return $this;
    }

    /**
     * Unsets aid field.
     */
    public function unsetAID(): self
    {
        $this->instance->unsetAID();
        return $this;
    }

    /**
     * Sets applab field.
     */
    public function aPPLAB(?string $value): self
    {
        $this->instance->setAPPLAB($value);
        return $this;
    }

    /**
     * Unsets applab field.
     */
    public function unsetAPPLAB(): self
    {
        $this->instance->unsetAPPLAB();
        return $this;
    }

    /**
     * Sets appn field.
     */
    public function aPPN(?string $value): self
    {
        $this->instance->setAPPN($value);
        return $this;
    }

    /**
     * Unsets appn field.
     */
    public function unsetAPPN(): self
    {
        $this->instance->unsetAPPN();
        return $this;
    }

    /**
     * Sets cvm field.
     */
    public function cVM(?string $value): self
    {
        $this->instance->setCVM($value);
        return $this;
    }

    /**
     * Unsets cvm field.
     */
    public function unsetCVM(): self
    {
        $this->instance->unsetCVM();
        return $this;
    }

    /**
     * Sets tsi field.
     */
    public function tSI(?string $value): self
    {
        $this->instance->setTSI($value);
        return $this;
    }

    /**
     * Unsets tsi field.
     */
    public function unsetTSI(): self
    {
        $this->instance->unsetTSI();
        return $this;
    }

    /**
     * Sets tvr field.
     */
    public function tVR(?string $value): self
    {
        $this->instance->setTVR($value);
        return $this;
    }

    /**
     * Unsets tvr field.
     */
    public function unsetTVR(): self
    {
        $this->instance->unsetTVR();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new emv receipt data object.
     */
    public function build(): EmvReceiptData
    {
        return CoreHelper::clone($this->instance);
    }
}
