<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\LineItem6;

/**
 * Builder for model LineItem6
 *
 * @see LineItem6
 */
class LineItem6Builder
{
    /**
     * @var LineItem6
     */
    private $instance;

    private function __construct(LineItem6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new line item 6 Builder object.
     */
    public static function init(
        string $description,
        string $commodityCode,
        string $productCode,
        string $unitCode,
        int $unitCost
    ): self {
        return new self(new LineItem6($description, $commodityCode, $productCode, $unitCode, $unitCost));
    }

    /**
     * Sets discount amount field.
     */
    public function discountAmount(?int $value): self
    {
        $this->instance->setDiscountAmount($value);
        return $this;
    }

    /**
     * Unsets discount amount field.
     */
    public function unsetDiscountAmount(): self
    {
        $this->instance->unsetDiscountAmount();
        return $this;
    }

    /**
     * Sets other tax amount field.
     */
    public function otherTaxAmount(?int $value): self
    {
        $this->instance->setOtherTaxAmount($value);
        return $this;
    }

    /**
     * Unsets other tax amount field.
     */
    public function unsetOtherTaxAmount(): self
    {
        $this->instance->unsetOtherTaxAmount();
        return $this;
    }

    /**
     * Sets quantity field.
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Unsets quantity field.
     */
    public function unsetQuantity(): self
    {
        $this->instance->unsetQuantity();
        return $this;
    }

    /**
     * Sets tax amount field.
     */
    public function taxAmount(?int $value): self
    {
        $this->instance->setTaxAmount($value);
        return $this;
    }

    /**
     * Unsets tax amount field.
     */
    public function unsetTaxAmount(): self
    {
        $this->instance->unsetTaxAmount();
        return $this;
    }

    /**
     * Sets tax rate field.
     */
    public function taxRate(?int $value): self
    {
        $this->instance->setTaxRate($value);
        return $this;
    }

    /**
     * Unsets tax rate field.
     */
    public function unsetTaxRate(): self
    {
        $this->instance->unsetTaxRate();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new line item 6 object.
     */
    public function build(): LineItem6
    {
        return CoreHelper::clone($this->instance);
    }
}
