<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Location4;

/**
 * Builder for model Location4
 *
 * @see Location4
 */
class Location4Builder
{
    /**
     * @var Location4
     */
    private $instance;

    private function __construct(Location4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new location 4 Builder object.
     */
    public static function init(string $phoneNumber): self
    {
        return new self(new Location4($phoneNumber));
    }

    /**
     * Sets address line 1 field.
     */
    public function addressLine1(?string $value): self
    {
        $this->instance->setAddressLine1($value);
        return $this;
    }

    /**
     * Unsets address line 1 field.
     */
    public function unsetAddressLine1(): self
    {
        $this->instance->unsetAddressLine1();
        return $this;
    }

    /**
     * Sets address line 2 field.
     */
    public function addressLine2(?string $value): self
    {
        $this->instance->setAddressLine2($value);
        return $this;
    }

    /**
     * Unsets address line 2 field.
     */
    public function unsetAddressLine2(): self
    {
        $this->instance->unsetAddressLine2();
        return $this;
    }

    /**
     * Sets city field.
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Unsets city field.
     */
    public function unsetCity(): self
    {
        $this->instance->unsetCity();
        return $this;
    }

    /**
     * Sets state province field.
     */
    public function stateProvince(?string $value): self
    {
        $this->instance->setStateProvince($value);
        return $this;
    }

    /**
     * Unsets state province field.
     */
    public function unsetStateProvince(): self
    {
        $this->instance->unsetStateProvince();
        return $this;
    }

    /**
     * Sets postal code field.
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Unsets postal code field.
     */
    public function unsetPostalCode(): self
    {
        $this->instance->unsetPostalCode();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new location 4 object.
     */
    public function build(): Location4
    {
        return CoreHelper::clone($this->instance);
    }
}
