<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Page;

/**
 * Builder for model Page
 *
 * @see Page
 */
class PageBuilder
{
    /**
     * @var Page
     */
    private $instance;

    private function __construct(Page $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new page Builder object.
     */
    public static function init(): self
    {
        return new self(new Page());
    }

    /**
     * Sets number field.
     */
    public function number(?int $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Sets size field.
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new page object.
     */
    public function build(): Page
    {
        return CoreHelper::clone($this->instance);
    }
}
