<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data1;
use FortisAPILib\Models\ResponseAsyncProcessing;

/**
 * Builder for model ResponseAsyncProcessing
 *
 * @see ResponseAsyncProcessing
 */
class ResponseAsyncProcessingBuilder
{
    /**
     * @var ResponseAsyncProcessing
     */
    private $instance;

    private function __construct(ResponseAsyncProcessing $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response async processing Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseAsyncProcessing());
    }

    /**
     * Sets data field.
     */
    public function data(?Data1 $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new response async processing object.
     */
    public function build(): ResponseAsyncProcessing
    {
        return CoreHelper::clone($this->instance);
    }
}
