<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Data28;
use FortisAPILib\Models\ResponseWebhook;

/**
 * Builder for model ResponseWebhook
 *
 * @see ResponseWebhook
 */
class ResponseWebhookBuilder
{
    /**
     * @var ResponseWebhook
     */
    private $instance;

    private function __construct(ResponseWebhook $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new response webhook Builder object.
     */
    public static function init(): self
    {
        return new self(new ResponseWebhook());
    }

    /**
     * Sets data field.
     */
    public function data(?Data28 $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new response webhook object.
     */
    public function build(): ResponseWebhook
    {
        return CoreHelper::clone($this->instance);
    }
}
