<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Sort30;

/**
 * Builder for model Sort30
 *
 * @see Sort30
 */
class Sort30Builder
{
    /**
     * @var Sort30
     */
    private $instance;

    private function __construct(Sort30 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new sort 30 Builder object.
     */
    public static function init(): self
    {
        return new self(new Sort30());
    }

    /**
     * Sets user id field.
     */
    public function userId(?array $value): self
    {
        $this->instance->setUserId($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?array $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets created ts field.
     */
    public function createdTs(?array $value): self
    {
        $this->instance->setCreatedTs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new sort 30 object.
     */
    public function build(): Sort30
    {
        return CoreHelper::clone($this->instance);
    }
}
