<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\Sort21;

/**
 * Builder for model Sort21
 *
 * @see Sort21
 */
class Sort21Builder
{
    /**
     * @var Sort21
     */
    private $instance;

    private function __construct(Sort21 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new sort 21 Builder object.
     */
    public static function init(): self
    {
        return new self(new Sort21());
    }

    /**
     * Sets location id field.
     */
    public function locationId(?array $value): self
    {
        $this->instance->setLocationId($value);
        return $this;
    }

    /**
     * Sets cc product transaction id field.
     */
    public function ccProductTransactionId(?array $value): self
    {
        $this->instance->setCcProductTransactionId($value);
        return $this;
    }

    /**
     * Sets email field.
     */
    public function email(?array $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets amount due field.
     */
    public function amountDue(?array $value): self
    {
        $this->instance->setAmountDue($value);
        return $this;
    }

    /**
     * Sets location api id field.
     */
    public function locationApiId(?array $value): self
    {
        $this->instance->setLocationApiId($value);
        return $this;
    }

    /**
     * Sets contact id field.
     */
    public function contactId(?array $value): self
    {
        $this->instance->setContactId($value);
        return $this;
    }

    /**
     * Sets contact api id field.
     */
    public function contactApiId(?array $value): self
    {
        $this->instance->setContactApiId($value);
        return $this;
    }

    /**
     * Sets paylink api id field.
     */
    public function paylinkApiId(?array $value): self
    {
        $this->instance->setPaylinkApiId($value);
        return $this;
    }

    /**
     * Sets ach product transaction id field.
     */
    public function achProductTransactionId(?array $value): self
    {
        $this->instance->setAchProductTransactionId($value);
        return $this;
    }

    /**
     * Sets expire date field.
     */
    public function expireDate(?array $value): self
    {
        $this->instance->setExpireDate($value);
        return $this;
    }

    /**
     * Sets display product transaction receipt details field.
     */
    public function displayProductTransactionReceiptDetails(?array $value): self
    {
        $this->instance->setDisplayProductTransactionReceiptDetails($value);
        return $this;
    }

    /**
     * Sets display billing fields field.
     */
    public function displayBillingFields(?array $value): self
    {
        $this->instance->setDisplayBillingFields($value);
        return $this;
    }

    /**
     * Sets delivery method field.
     */
    public function deliveryMethod(?array $value): self
    {
        $this->instance->setDeliveryMethod($value);
        return $this;
    }

    /**
     * Sets cell phone field.
     */
    public function cellPhone(?array $value): self
    {
        $this->instance->setCellPhone($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?array $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets store token field.
     */
    public function storeToken(?array $value): self
    {
        $this->instance->setStoreToken($value);
        return $this;
    }

    /**
     * Sets store token title field.
     */
    public function storeTokenTitle(?array $value): self
    {
        $this->instance->setStoreTokenTitle($value);
        return $this;
    }

    /**
     * Sets paylink action field.
     */
    public function paylinkAction(?array $value): self
    {
        $this->instance->setPaylinkAction($value);
        return $this;
    }

    /**
     * Sets bank funded only override field.
     */
    public function bankFundedOnlyOverride(?array $value): self
    {
        $this->instance->setBankFundedOnlyOverride($value);
        return $this;
    }

    /**
     * Sets tags field.
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?array $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets status id field.
     */
    public function statusId(?array $value): self
    {
        $this->instance->setStatusId($value);
        return $this;
    }

    /**
     * Sets status code field.
     */
    public function statusCode(?array $value): self
    {
        $this->instance->setStatusCode($value);
        return $this;
    }

    /**
     * Sets active field.
     */
    public function active(?array $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets created ts field.
     */
    public function createdTs(?array $value): self
    {
        $this->instance->setCreatedTs($value);
        return $this;
    }

    /**
     * Sets modified ts field.
     */
    public function modifiedTs(?array $value): self
    {
        $this->instance->setModifiedTs($value);
        return $this;
    }

    /**
     * Sets created user id field.
     */
    public function createdUserId(?array $value): self
    {
        $this->instance->setCreatedUserId($value);
        return $this;
    }

    /**
     * Sets modified user id field.
     */
    public function modifiedUserId(?array $value): self
    {
        $this->instance->setModifiedUserId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new sort 21 object.
     */
    public function build(): Sort21
    {
        return CoreHelper::clone($this->instance);
    }
}
