<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use FortisAPILib\Models\V1TagsRequest1;

/**
 * Builder for model V1TagsRequest1
 *
 * @see V1TagsRequest1
 */
class V1TagsRequest1Builder
{
    /**
     * @var V1TagsRequest1
     */
    private $instance;

    private function __construct(V1TagsRequest1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new v1 tags request 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new V1TagsRequest1());
    }

    /**
     * Sets location id field.
     */
    public function locationId(?string $value): self
    {
        $this->instance->setLocationId($value);
        return $this;
    }

    /**
     * Unsets location id field.
     */
    public function unsetLocationId(): self
    {
        $this->instance->unsetLocationId();
        return $this;
    }

    /**
     * Sets title field.
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Unsets title field.
     */
    public function unsetTitle(): self
    {
        $this->instance->unsetTitle();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new v1 tags request 1 object.
     */
    public function build(): V1TagsRequest1
    {
        return CoreHelper::clone($this->instance);
    }
}
