<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Account Type
 */
class AccountTypeEnum
{
    public const UNKNOWN = 'unknown';

    public const CHECKING = 'checking';

    public const CREDIT = 'credit';

    public const CASH_BENEFIT = 'cash_benefit';

    public const SNAP = 'snap';

    public const PREPAID = 'prepaid';

    public const SAVINGS = 'savings';

    public const SPENDING_POWER = 'spending_power';

    public const UNIVERSAL = 'universal';

    private const _ALL_VALUES = [
        self::UNKNOWN,
        self::CHECKING,
        self::CREDIT,
        self::CASH_BENEFIT,
        self::SNAP,
        self::PREPAID,
        self::SAVINGS,
        self::SPENDING_POWER,
        self::UNIVERSAL
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AccountTypeEnum.");
    }
}
