<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The Type of a merchant's business.
 */
class BusinessTypeEnum
{
    public const ACCOUNTING = 'accounting';

    public const ACUPUNCTURE = 'acupuncture';

    public const AIRLINES = 'airlines';

    public const ALTERNATIVE_MEDICINE = 'alternative_medicine';

    public const ART_PHOTO_AND_FILM = 'art_photo_and_film';

    public const AUTOMOBILE_ASSOCIATION = 'automobile_association';

    public const AUTOMOTIVE_SERVICES = 'automotive_services';

    public const BAKERY = 'bakery';

    public const BAR_CLUB_LOUNGE = 'bar_club_lounge';

    public const BEAUTY_SALON = 'beauty_salon';

    public const BOOKS_MAGS_MUSIC_AND_VIDEO = 'books_mags_music_and_video';

    public const BUS = 'bus';

    public const CAR_RENTAL = 'car_rental';

    public const CARE_GIVER = 'care_giver';

    public const CARPET_CLEANING = 'carpet_cleaning';

    public const CATERER = 'caterer';

    public const CHARITABLE_ORGANIZATION = 'charitable_organization';

    public const CHILD_CARE = 'child_care';

    public const CHIROPRACTOR = 'chiropractor';

    public const CIVIC_SOCIAL_AND_FRATERNAL_ASSOCIATION = 'civic_social_and_fraternal_association';

    public const CLEANING = 'cleaning';

    public const CLOTHING_ALTERATIONS = 'clothing_alterations';

    public const CLOTHING_AND_ACCESSORIES = 'clothing_and_accessories';

    public const COFFEE_TEA_SHOP = 'coffee_tea_shop';

    public const COMPUTER_ELECTRONICS_AND_APPLIANCE_REPAIR = 'computer_electronics_and_appliance_repair';

    public const CONSULTING = 'consulting';

    public const CONVENIENCE_STORE = 'convenience_store';

    public const DELIVERY = 'delivery';

    public const DENTIST_ORTHODONTIST = 'dentist_orthodontist';

    public const DESIGN = 'design';

    public const DRY_CLEANING_AND_LAUNDRY = 'dry_cleaning_and_laundry';

    public const ELECTRICAL_SERVICES = 'electrical_services';

    public const ELECTRONICS = 'electronics';

    public const EVENTS_FESTIVALS = 'events_festivals';

    public const EYEWEAR = 'eyewear';

    public const FLOORING = 'flooring';

    public const FLOWERS_AND_GIFTS = 'flowers_and_gifts';

    public const FOOD_TRUCK_CART = 'food_truck_cart';

    public const FURNITURE_HOME_GOODS = 'furniture_home_goods';

    public const GENERAL_CONTRACTING = 'general_contracting';

    public const GROCERY_MARKET = 'grocery_market';

    public const GYM_HEALTH_CLUB = 'gym_health_club';

    public const HAIR_SALON_BARBERSHOP = 'hair_salon_barbershop';

    public const HARDWARE_STORE = 'hardware_store';

    public const HEATING_AND_AIR_CONDITIONING = 'heating_and_air_conditioning';

    public const HOBBY_SHOP = 'hobby_shop';

    public const INDEPENDENT_STYLIST_BARBER = 'independent_stylist_barber';

    public const INSTALLATION_SERVICES = 'installation_services';

    public const INSTRUCTOR_TEACHER = 'instructor_teacher';

    public const INTERIOR_DESIGN = 'interior_design';

    public const JEWELRY_AND_WATCHES = 'jewelry_and_watches';

    public const JUNK_REMOVAL = 'junk_removal';

    public const LANDSCAPING = 'landscaping';

    public const LEGAL_SERVICES = 'legal_services';

    public const LIMOUSINE = 'limousine';

    public const LOCKSMITH_SERVICES = 'locksmith_services';

    public const LODGING = 'lodging';

    public const MARKETING_ADVERTISING = 'marketing_advertising';

    public const MASSAGE_THERAPIST = 'massage_therapist';

    public const MEDICAL_PRACTITIONER = 'medical_practitioner';

    public const MEMBERSHIP_ORGANIZATION = 'membership_organization';

    public const MISCELLANEOUS_GOODS = 'miscellaneous_goods';

    public const MISCELLANEOUS_SERVICES = 'miscellaneous_services';

    public const MOVIES_FILM = 'movies_film';

    public const MOVING = 'moving';

    public const MUSEUM_CULTURAL = 'museum_cultural';

    public const MUSIC = 'music';

    public const NAIL_SALON = 'nail_salon';

    public const NANNY_SERVICES = 'nanny_services';

    public const NOTARY_SERVICES = 'notary_services';

    public const OFFICE_SUPPLY = 'office_supply';

    public const OPTOMETRIST_LASER_EYE_SURGERY = 'optometrist_laser_eye_surgery';

    public const OTHER = 'other';

    public const OUTDOOR_MARKETS = 'outdoor_markets';

    public const PAINTING = 'painting';

    public const PERFORMING_ARTS = 'performing_arts';

    public const PERSONAL_TRAINER = 'personal_trainer';

    public const PEST_CONTROL = 'pest_control';

    public const PET_STORE = 'pet_store';

    public const PHOTOGRAPHY = 'photography';

    public const PLUMBING = 'plumbing';

    public const POLITICAL_ORGANIZATION = 'political_organization';

    public const PRINTING_SERVICES = 'printing_services';

    public const PRIVATE_CHEF = 'private_chef';

    public const PRIVATE_SHUTTLE = 'private_shuttle';

    public const PSYCHIATRIST = 'psychiatrist';

    public const QUICK_SERVICE_RESTAURANT = 'quick_service_restaurant';

    public const REAL_ESTATE = 'real_estate';

    public const RELIGIOUS_ORGANIZATION = 'religious_organization';

    public const ROOFING = 'roofing';

    public const SCHOOL = 'school';

    public const SHOE_REPAIR = 'shoe_repair';

    public const SIT_DOWN_RESTAURANT = 'sit_down_restaurant';

    public const SOFTWARE_DEVELOPMENT = 'software_development';

    public const SPA = 'spa';

    public const SPECIALTY_SHOP = 'specialty_shop';

    public const SPORTING_EVENTS = 'sporting_events';

    public const SPORTING_GOODS = 'sporting_goods';

    public const SPORTS_RECREATION = 'sports_recreation';

    public const TANNING_SALON = 'tanning_salon';

    public const TATTOO_PIERCING = 'tattoo_piercing';

    public const TAXI = 'taxi';

    public const THERAPIST = 'therapist';

    public const TOURISM = 'tourism';

    public const TOWN_CAR = 'town_car';

    public const TUTOR = 'tutor';

    public const VETERINARY_SERVICES = 'veterinary_services';

    public const WATCH_JEWELRY_REPAIR = 'watch_jewelry_repair';

    private const _ALL_VALUES = [
        self::ACCOUNTING,
        self::ACUPUNCTURE,
        self::AIRLINES,
        self::ALTERNATIVE_MEDICINE,
        self::ART_PHOTO_AND_FILM,
        self::AUTOMOBILE_ASSOCIATION,
        self::AUTOMOTIVE_SERVICES,
        self::BAKERY,
        self::BAR_CLUB_LOUNGE,
        self::BEAUTY_SALON,
        self::BOOKS_MAGS_MUSIC_AND_VIDEO,
        self::BUS,
        self::CAR_RENTAL,
        self::CARE_GIVER,
        self::CARPET_CLEANING,
        self::CATERER,
        self::CHARITABLE_ORGANIZATION,
        self::CHILD_CARE,
        self::CHIROPRACTOR,
        self::CIVIC_SOCIAL_AND_FRATERNAL_ASSOCIATION,
        self::CLEANING,
        self::CLOTHING_ALTERATIONS,
        self::CLOTHING_AND_ACCESSORIES,
        self::COFFEE_TEA_SHOP,
        self::COMPUTER_ELECTRONICS_AND_APPLIANCE_REPAIR,
        self::CONSULTING,
        self::CONVENIENCE_STORE,
        self::DELIVERY,
        self::DENTIST_ORTHODONTIST,
        self::DESIGN,
        self::DRY_CLEANING_AND_LAUNDRY,
        self::ELECTRICAL_SERVICES,
        self::ELECTRONICS,
        self::EVENTS_FESTIVALS,
        self::EYEWEAR,
        self::FLOORING,
        self::FLOWERS_AND_GIFTS,
        self::FOOD_TRUCK_CART,
        self::FURNITURE_HOME_GOODS,
        self::GENERAL_CONTRACTING,
        self::GROCERY_MARKET,
        self::GYM_HEALTH_CLUB,
        self::HAIR_SALON_BARBERSHOP,
        self::HARDWARE_STORE,
        self::HEATING_AND_AIR_CONDITIONING,
        self::HOBBY_SHOP,
        self::INDEPENDENT_STYLIST_BARBER,
        self::INSTALLATION_SERVICES,
        self::INSTRUCTOR_TEACHER,
        self::INTERIOR_DESIGN,
        self::JEWELRY_AND_WATCHES,
        self::JUNK_REMOVAL,
        self::LANDSCAPING,
        self::LEGAL_SERVICES,
        self::LIMOUSINE,
        self::LOCKSMITH_SERVICES,
        self::LODGING,
        self::MARKETING_ADVERTISING,
        self::MASSAGE_THERAPIST,
        self::MEDICAL_PRACTITIONER,
        self::MEMBERSHIP_ORGANIZATION,
        self::MISCELLANEOUS_GOODS,
        self::MISCELLANEOUS_SERVICES,
        self::MOVIES_FILM,
        self::MOVING,
        self::MUSEUM_CULTURAL,
        self::MUSIC,
        self::NAIL_SALON,
        self::NANNY_SERVICES,
        self::NOTARY_SERVICES,
        self::OFFICE_SUPPLY,
        self::OPTOMETRIST_LASER_EYE_SURGERY,
        self::OTHER,
        self::OUTDOOR_MARKETS,
        self::PAINTING,
        self::PERFORMING_ARTS,
        self::PERSONAL_TRAINER,
        self::PEST_CONTROL,
        self::PET_STORE,
        self::PHOTOGRAPHY,
        self::PLUMBING,
        self::POLITICAL_ORGANIZATION,
        self::PRINTING_SERVICES,
        self::PRIVATE_CHEF,
        self::PRIVATE_SHUTTLE,
        self::PSYCHIATRIST,
        self::QUICK_SERVICE_RESTAURANT,
        self::REAL_ESTATE,
        self::RELIGIOUS_ORGANIZATION,
        self::ROOFING,
        self::SCHOOL,
        self::SHOE_REPAIR,
        self::SIT_DOWN_RESTAURANT,
        self::SOFTWARE_DEVELOPMENT,
        self::SPA,
        self::SPECIALTY_SHOP,
        self::SPORTING_EVENTS,
        self::SPORTING_GOODS,
        self::SPORTS_RECREATION,
        self::TANNING_SALON,
        self::TATTOO_PIERCING,
        self::TAXI,
        self::THERAPIST,
        self::TOURISM,
        self::TOWN_CAR,
        self::TUTOR,
        self::VETERINARY_SERVICES,
        self::WATCH_JEWELRY_REPAIR
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for BusinessTypeEnum.");
    }
}
