<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class Expand5Enum
{
    public const CREATED_USER = 'created_user';

    public const LOCATION = 'location';

    public const TERMINAL = 'terminal';

    public const CHANGELOGS = 'changelogs';

    public const SIGNATURE = 'signature';

    public const REASON_CODE = 'reason_code';

    private const _ALL_VALUES =
        [self::CREATED_USER, self::LOCATION, self::TERMINAL, self::CHANGELOGS, self::SIGNATURE, self::REASON_CODE];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Expand5Enum.");
    }
}
