<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

/**
 * Identity Verification
 */
class IdentityVerification17 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $dlState;

    /**
     * @var string
     */
    private $dlNumber;

    /**
     * @var array
     */
    private $ssn4 = [];

    /**
     * @var array
     */
    private $dobYear = [];

    /**
     * @param string $dlState
     * @param string $dlNumber
     */
    public function __construct(string $dlState, string $dlNumber)
    {
        $this->dlState = $dlState;
        $this->dlNumber = $dlNumber;
    }

    /**
     * Returns Dl State.
     * Required for ACH transactions when Driver's License Verification is enabled on the terminal.  Either
     * dl_number + dl_state OR customer_id will need to be passed in this scenario.
     */
    public function getDlState(): string
    {
        return $this->dlState;
    }

    /**
     * Sets Dl State.
     * Required for ACH transactions when Driver's License Verification is enabled on the terminal.  Either
     * dl_number + dl_state OR customer_id will need to be passed in this scenario.
     *
     * @required
     * @maps dl_state
     */
    public function setDlState(string $dlState): void
    {
        $this->dlState = $dlState;
    }

    /**
     * Returns Dl Number.
     * Required for ACH transactions when Driver's License Verification is enabled on the terminal.  Either
     * dl_number + dl_state OR customer_id will need to be passed in this scenario.
     */
    public function getDlNumber(): string
    {
        return $this->dlNumber;
    }

    /**
     * Sets Dl Number.
     * Required for ACH transactions when Driver's License Verification is enabled on the terminal.  Either
     * dl_number + dl_state OR customer_id will need to be passed in this scenario.
     *
     * @required
     * @maps dl_number
     */
    public function setDlNumber(string $dlNumber): void
    {
        $this->dlNumber = $dlNumber;
    }

    /**
     * Returns Ssn 4.
     * For ACH transactions where Identity Verification is enabled for terminal. Only ssn4 or dob_year
     * should be passed. not both.
     */
    public function getSsn4(): ?string
    {
        if (count($this->ssn4) == 0) {
            return null;
        }
        return $this->ssn4['value'];
    }

    /**
     * Sets Ssn 4.
     * For ACH transactions where Identity Verification is enabled for terminal. Only ssn4 or dob_year
     * should be passed. not both.
     *
     * @maps ssn4
     */
    public function setSsn4(?string $ssn4): void
    {
        $this->ssn4['value'] = $ssn4;
    }

    /**
     * Unsets Ssn 4.
     * For ACH transactions where Identity Verification is enabled for terminal. Only ssn4 or dob_year
     * should be passed. not both.
     */
    public function unsetSsn4(): void
    {
        $this->ssn4 = [];
    }

    /**
     * Returns Dob Year.
     * Required for certain ACH transactions where Identity Verification has been enabled for the terminal.
     * Either ssn4 or dob_year will need to be passed in this scenario but NOT BOTH.
     */
    public function getDobYear(): ?string
    {
        if (count($this->dobYear) == 0) {
            return null;
        }
        return $this->dobYear['value'];
    }

    /**
     * Sets Dob Year.
     * Required for certain ACH transactions where Identity Verification has been enabled for the terminal.
     * Either ssn4 or dob_year will need to be passed in this scenario but NOT BOTH.
     *
     * @maps dob_year
     */
    public function setDobYear(?string $dobYear): void
    {
        $this->dobYear['value'] = $dobYear;
    }

    /**
     * Unsets Dob Year.
     * Required for certain ACH transactions where Identity Verification has been enabled for the terminal.
     * Either ssn4 or dob_year will need to be passed in this scenario but NOT BOTH.
     */
    public function unsetDobYear(): void
    {
        $this->dobYear = [];
    }

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property
     * @param mixed $value Value of property
     */
    public function addAdditionalProperty(string $name, $value)
    {
        $this->additionalProperties[$name] = $value;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['dl_state']     = $this->dlState;
        $json['dl_number']    = $this->dlNumber;
        if (!empty($this->ssn4)) {
            $json['ssn4']     = $this->ssn4['value'];
        }
        if (!empty($this->dobYear)) {
            $json['dob_year'] = $this->dobYear['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
