<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Reason Model
 */
class ReasonModelEnum
{
    public const CONTACT = 'Contact';

    public const TRANSACTION = 'Transaction';

    public const RECURRING = 'Recurring';

    public const USER = 'User';

    public const PRODUCTTRANSACTION = 'ProductTransaction';

    public const TRANSACTIONBATCH = 'TransactionBatch';

    public const QUICKINVOICE = 'QuickInvoice';

    public const DATAEXPORT = 'DataExport';

    public const USERREPORTSCHEDULE = 'UserReportSchedule';

    public const USERREPORT = 'UserReport';

    public const PAYLINK = 'Paylink';

    private const _ALL_VALUES = [
        self::CONTACT,
        self::TRANSACTION,
        self::RECURRING,
        self::USER,
        self::PRODUCTTRANSACTION,
        self::TRANSACTIONBATCH,
        self::QUICKINVOICE,
        self::DATAEXPORT,
        self::USERREPORTSCHEDULE,
        self::USERREPORT,
        self::PAYLINK
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ReasonModelEnum.");
    }
}
