<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * type of the amount [4S-Healthcare(Visa and MC Only), 4U-Prescription/Rx(Visa and MC Only), 4V-
 * Vision/Optical(Visa Only), 4W-clinic/other qualified medical(Visa Only) ,4X-Dental(Visa Only)].
 */
class Type1Enum
{
    public const CASHBACK = 'cashback';

    public const SURCHARGE = 'surcharge';

    public const HEALTHCARE = 'healthcare';

    public const TRANSIT = 'transit';

    public const RX = 'RX';

    public const VISION = 'vision';

    public const CLINICAL = 'clinical';

    public const COPAY = 'copay';

    public const DENTAL = 'dental';

    public const TAX = 'tax';

    public const FEE = 'fee';

    private const _ALL_VALUES = [
        self::CASHBACK,
        self::SURCHARGE,
        self::HEALTHCARE,
        self::TRANSIT,
        self::RX,
        self::VISION,
        self::CLINICAL,
        self::COPAY,
        self::DENTAL,
        self::TAX,
        self::FEE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Type1Enum.");
    }
}
